[package]
name = "radial-chess"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.15"
futures = "0.3"
log = "0.4"
env_logger = "0.9"
pleco = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
