name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up sshpass
        run: sudo apt-get install -y sshpass

      - name: Authenticate Docker to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          IMAGE_NAME: ghcr.io/jwhogg/radial-chess-backend/radial_chess_server
          CONTAINER_NAME: radial_chess_server
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          # Use sshpass to login via password and run commands on the VPS
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
              # Authenticate Docker on VPS
              echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
              
              # Stop and remove the old container if it exists
              docker stop $CONTAINER_NAME || true
              docker rm $CONTAINER_NAME || true
              
              # Pull the latest image from GHCR
              docker pull $IMAGE_NAME:latest
              
              # Run the new container (adjust the port mapping as necessary)
              docker run -d --name $CONTAINER_NAME -p 80:80 -p 8080:8080 $IMAGE_NAME:latest
          EOF
